defaults: &defaults
  working_directory: ~/chat-online-backend
  docker:
    - image: circleci/node:12.13.0
  environment:
    PROJECT_NAME: chat-online-backend

version: 2.1
jobs:
  build-image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: docker build -t huanhiendanh/chat-online-backend .

  build-push-deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build push and deploy
          command: |
            sudo chmod 777 ./deployments/deploy.sh
            ./deployments/deploy.sh

workflows:
  version: 2
  build-push-and-deploy:
    jobs:
      - build-image

      - build-push-deploy:
          requires:
            - build-image
          filters:
            branches:
              only: master
